# Generated by Django 5.1.2 on 2024-11-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_room_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.ImageField(default=' ', upload_to='images'),
        ),
    ]
