# Generated by Django 5.1.2 on 2024-11-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_room_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='null')),
                ('images', models.ImageField(default=' ', upload_to='images')),
            ],
        ),
    ]
