# Generated by Django 5.1.2 on 2024-11-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image2',
            field=models.ImageField(default=' ', upload_to='images'),
        ),
        migrations.AddField(
            model_name='room',
            name='image3',
            field=models.ImageField(default=' ', upload_to='images'),
        ),
        migrations.AddField(
            model_name='room',
            name='image4',
            field=models.ImageField(default=' ', upload_to='images'),
        ),
    ]
