# Generated by Django 5.1.2 on 2024-12-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_room_total_rooms_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['check_in_date']},
        ),
    ]
