# Generated by Django 5.1.2 on 2024-12-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.RemoveField(
            model_name='room',
            name='availability_status',
        ),
    ]
