# Generated by Django 5.1.2 on 2024-12-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_booking_user_payment_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
