# Generated by Django 5.1.2 on 2024-12-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_review_booking_alter_review_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Khalti', 'Khalti'), ('e-Sewa', 'e-Sewa'), ('cash', 'Cash')], max_length=50),
        ),
    ]
