# Generated by Django 5.1.2 on 2024-12-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
