# Generated by Django 5.1.2 on 2024-12-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_payment_payment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
