# Generated by Django 5.1.2 on 2024-12-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_nights',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
