# Generated by Django 5.1.2 on 2024-12-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='esewa_ref_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
