# Generated by Django 5.1.2 on 2024-12-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_payment_esewa_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='esewa_ref_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
    ]
