# Generated by Django 5.1.2 on 2024-12-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_guestprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestprofile',
            name='profile_picture',
            field=models.ImageField(default='/static/images/default-profile.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
