# Generated by Django 5.1.2 on 2024-12-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_guestprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Message',
        ),
    ]
