# Generated by Django 5.1.2 on 2025-01-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_customer_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestprofile',
            name='profile_picture',
            field=models.ImageField(default='../static/images/default-profile.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
