# Generated by Django 5.1.2 on 2025-01-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_guestprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-profile.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
