# Generated by Django 5.1.2 on 2025-01-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_guestprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
